## Trabalho 01 - Grafos

- Aluno: Dayvison Gomes de Oliveira
- Matrícula: 20180036876
- Professor: Teobaldo Leite

In [1]:
import numpy as np

## Exibindo a matriz de adjacência.

In [2]:
def load_print(path):
    arq = open(path,'r')

    G = [linha.rstrip() for linha in arq]
    G[0] = int(G[0])
    n_V = G[0]
    G.remove(n_V)

    for i in range(len(G)):
        G[i] = G[i].split(' ')
    
        for j in range(len(G[i])):
            G[i][j] = int(G[i][j])
    
    arq.close()
    
    print('Matriz de adjacência: \n')
    for i in range(len(G)):
        
        print(f'{i} -> {G[i]}')
    
    return n_V, np.array(G)

n_V,G = load_print('Modelo_de_grafo.txt')

Matriz de adjacência: 

0 -> [0, 1, 1, 1, 0, 0, 0]
1 -> [1, 0, 1, 1, 0, 0, 0]
2 -> [1, 1, 0, 1, 1, 1, 0]
3 -> [1, 1, 1, 0, 0, 0, 0]
4 -> [0, 0, 1, 0, 0, 1, 1]
5 -> [0, 0, 1, 0, 1, 0, 1]
6 -> [0, 0, 0, 0, 1, 1, 0]


##  Graus mínimo $(\delta(G))$, máximo $(∆(G))$ e médio / Sequência de graus de $G$.

In [12]:
def Graus(n_V,G):
    graus = []
    m = 0
    
    for i in range(len(G)):
        graus.append(G[i].sum())
    
    graus = np.array(graus)
    
    print(f'\nGrau mínimo: {graus[np.argmin(graus)]} -> Vértice: {np.argmin(graus)+1}  ')
    print(f'Grau máximo: {graus[np.argmax(graus)]} -> Vértice: {np.argmax(graus)+1}  ')
    
    for i in range(len(G)):
        for j in range(len(G[i])):
            if G[i][j] == 1:
                m += 1
    
    print(f'Grau médio: {m/n_V}')
        
    print(f'\nSequencia de Graus: {np.sort(graus)}')
    
    return graus

graus = Graus(n_V,G)


Grau mínimo: 2 -> Vértice: 7  
Grau máximo: 5 -> Vértice: 3  
Grau médio: 3.142857142857143

Sequencia de Graus: [2 3 3 3 3 3 5]


## Grau e as vizinhanças aberta e fechada de um vértice v informado pelo usuário.

In [9]:
def neighborhood(G, graus):
    
    v = int(input('\nInsira o número de um vértice: '))
    
    while (v > (n_V-1)):
        print('Erro, vértice não existe, insira um que exista da lista abaixo')
        print(f'Os vértices vão de 0 até {n_V-1}\n')
        v = int(input(': '))
    
    print(f'\nO vértice {v} possui {graus[v]} graus ')
    
    v_Ligados = []
    for i in range(len(G[v])):
        if G[v][i] == 1:
            v_Ligados.append(i)
    
    v_Ligados.append(v)
    
    v_Ligados = np.array(v_Ligados)
    
    print(f'O vértice tem a vizinhança {v_Ligados[:-1]} aberta')
    print(f'O vértice tem a vizinhança {np.sort(v_Ligados)} fechada')

neighborhood(G, graus)


Insira o número de um vértice: 4

O vértice 4 possui 3 graus 
O vértice tem a vizinhança [2 5 6] aberta
O vértice tem a vizinhança [2 4 5 6] fechada


## Determinar se dois vértices u e v informados pelo usuário são vizinhos.

In [10]:
def neighbor(G):
    
    u = int(input('\nInsira um vértice u: '))
    v = int(input('Insira um vértice v: '))
    
    if G[u][v] == 1:
        print('\nSão vizinhos')
    else:
        print('\nNão são vizinhos')

neighbor(G)


Insira um vértice u: 2
Insira um vértice v: 3

São vizinhos


## Informar se o grafo é k-regular, deixando claro o valor de k.

In [11]:
def regular(graus):

    k = int(input('\nDigite um valor de k: '))
    
    if np.mean(graus) == k:
        print(f'\nÉ {k}-regular')
    
    else:
        print(f'\nNão é {k}-regular')

regular(graus)


Digite um valor de k: 3

Não é 3-regular


## Informar se G é completo.

In [13]:
def complete(graus):
    
    if (np.mean(graus) == n_V - 1):
        print('\nO grafo é completo')
        
    else:
        print('\nO grafo não é completo')

complete(graus)


O grafo não é completo


## Listar todos os vértices universais de G.

In [14]:
def universal(graus):
    
    v_Universal = []
    
    for i in range(len(graus)):
        if (graus[i] == n_V - 1):
            v_Universal.append(i)
    
    if len(v_Universal) == 0:
        print('\nEste grafo não possui vértices universais')
    
    else:
        print(f'\nLista com os vértices universais: {np.sort(v_Universal)}')

universal(graus)


Este grafo não possui vértices universais


## Listar todos os vértices isolados de G.

In [15]:
def isolated(graus):
    
    v_Isolados = []
    
    for i in range(len(graus)):
        if graus[i] == 0:
            v_Isolados.append(i)
     
    if len(v_Isolados) == 0:
        print('\nEste grafo não possui vértices isolados')
    
    else:
        print(f'\nLista com os vértices isolados: {np.sort(v_Isolados)}')
        
isolated(graus)


Este grafo não possui vértices isolados


## Determinar o subgrafo de $G$ induzido por um conjunto de vértices $S ⊆ V(G)$ informado pelo usuário. Tal subgrafo é denotado por $G[S]$.

In [17]:
def subgraph_V(G):
     
    n = input("\nDigite uma sequência de vértices (ex: 0,2,3 ):  ").split(',')
    vert = [int(i) for i in n]
    tam = len(vert)
    
    H = np.zeros((tam,tam))
    
    print('\nSubgrafo Induzido G[S]: ')
    
    for i in range(len(G)):
        for j in range(len(G[i])):
            if G[i][j] == 1 and i in vert and j in vert:
                H[i][j] = 1
            
    print(f'\n{H}')

subgraph_V(G) 


Digite uma sequência de vértices (ex: 0,2,3 ):  0,1,2

Subgrafo Induzido G[S]: 

[[0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 0.]]


## Determinar o subgrafo de $G$ induzido por um conjunto de arestas $E^{'} ⊆ E(G)$ informado pelo usuário. Tal subgrafo é denotado por $G[E^{'}]$.

In [18]:
def subgraph_E(n_V,G):
    
    arestas = input("\nDigite uma sequência de arestas (ex: 01,12,23): ").split(',')
    
    aux = [(int(num[0]), int(num[1])) for num in arestas]
    
    arestas = np.array(aux)
    tam = len(np.unique(arestas))
    S = np.zeros((n_V,n_V))
    
    print("\nSubgrafo Induzido G[E']: ")
    for tupla in arestas:
        if G[tupla[0]][tupla[1]] == 1:
            S[tupla[0]][tupla[1]] = 1
            S[tupla[1]][tupla[0]] = 1
    
    print(f"\n{S}")

subgraph_E(n_V,G)


Digite uma sequência de arestas (ex: 01,12,23): 01,13,56

Subgrafo Induzido G[E']: 

[[0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0.]]


## Decidir se uma sequência de vêrtices $v_{1}, v_2, ..., v_k$ informada pelo usuário representa um passeio em $G$. Em casa afirmativo, informar se o passeio também constitui um ciclo ou um caminho.

In [20]:
def walk(G):
    
    n = input("\nDigite uma sequência de vértices (ex: 0,2,3 ):  ").split(',')
    
    seq_v = [int(num) for num in n]
    
    passeio = True
    caminho = True
    
    aux_dic = {}
        
    for v in np.unique(seq_v):
        aux_dic[v] = False
    
    for j in range(len(seq_v)-1):
        if G[seq_v[j]][seq_v[j+1]] == 0:
            print('\nNão é um passeio')
            passeio = False       
            break
        
        else:
            if aux_dic[seq_v[j]] == False:
                aux_dic[seq_v[j]] = True
            
            else:
                caminho = False
    
    if aux_dic[seq_v[-1]] == True and seq_v[-1] != seq_v[0]:
        caminho = False

    if passeio:
        print('\nÉ um passeio')
        
        if caminho:
    
            if seq_v[-1] == seq_v[0]:
                print('\nE também é um ciclo')
    
            else:
                print('\nE também é um caminho')

walk(G)


Digite uma sequência de vértices (ex: 0,2,3 ):  0,1,2,3,0

É um passeio

E também é um ciclo


## Determinar se um conjunto de vértices $S ⊆ V(G)$ informado pelo usuário é uma clique de $G$. Em caso afirmativo, informar se a clique é maximal.

In [45]:
def click(G):
    n = input("\nDigite uma sequência de vértices (ex: 0,2,3 ):  ").split(',')
    
    seq_v = [int(num) for num in n]
    tamanho = len(seq_v)
    H = np.zeros((tamanho,tamanho))
    
    graus = []
    
    for i in range(len(G)):
        for j in range(len(G[i])):
            if G[i][j] == 1 and i in seq_v and j in seq_v:
                H[i][j] = 1
    
    print(f'\n{H}')
    
    for i in range(len(H)):
        graus.append(H[i].sum())
    
    graus = np.array(graus)
    cont = 0
    
    for i in range(len(graus)-1):
        if graus[i] == graus[i+1]:
            cont += 1
        else:
            break
    
    if cont == len(graus) - 1:
        print("\nO subgrafo acima é uma clique de G")
    else:
        print("\nO subgrafo acima não é uma clique de G")
    
        
click(G)


Digite uma sequência de vértices (ex: 0,2,3 ):  0,1,2,3,4

[[0. 1. 1. 1. 0.]
 [1. 0. 1. 1. 0.]
 [1. 1. 0. 1. 1.]
 [1. 1. 1. 0. 0.]
 [0. 0. 1. 0. 0.]]

O subgrafo acima não é uma clique de G
